relative_url: adfssdsdgs 
theme: jekyll-theme-minimal
# logo: logo.png
title: Escape-Exo4
description: A splinter session at the Exoplanets 4 conference
when: [Wednesday, May 4th 2022, 1 PM PT.]
where: [The M Resort, Milan room, Las Vegas NV.]
